---
apiVersion: v1
kind: Service
metadata:
  name: algorand
  labels:
    app: algorand
spec:
  clusterIP: None
  selector:
    app: algorand
  ports:
  - name: algod
    port: 4001
    targetPort: algod
  #- name: kmd
  #  port: 4002
  #  targetPort: kmd
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: algorand
spec:
  selector:
    matchLabels:
      app: algorand
  template:
    metadata:
      labels:
        app: algorand
    spec:
      containers:
      - name: algod
        image: algo_testnet
        command:
          - /bin/sh
          - -c
          - ./goal network start -r /network && sleep infinity
        ports:
          - containerPort: 4001
            name: algod
            protocol: TCP
        readinessProbe:
          tcpSocket:
            port: 4001
          initialDelaySeconds: 3
