apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-server
  labels:
    app: http-server
spec:
  selector:
    matchLabels:
      app: http-server
  template:
    metadata:
      labels:
        app: http-server
    spec:
      containers:
      - name: my-http-server
        image: http-server-image
        ports:
        - containerPort: 1234
        #livenessProbe:
        #  httpGet:
        #    path: /health
        #    port: 1234
        #  initialDelaySeconds: 3
        #  periodSeconds: 3

